### PR TITLE
Mount volume to Spark containers to use as a local directory for shuffles

### PR DESCRIPTION
**Pull request by fnothaft**
Relies on https://github.com/BD2KGenomics/cgl-docker-lib/pull/69.

@almussel can you test this on your current cluster?

### CODE REVIEW

**Comment by heuermh** [comment]
BD2KGenomics/cgl-docker-lib#69 is closed, can this be merged?

**Comment by fnothaft** [comment]
@almussel can you confirm that you have tested this? If you have tested this, we can remove the `needs work` tag and merge.

**Comment by almussel** [comment]
Yes, this has been tested. I was waiting on the NA12878 run to give the go
ahead but I think that's probably not necessary.

**Comment by hannes-ucsc** [comment]
Continued in #94.

My merge tool did not show any conflicts during the rebase so I just went ahead.

**Pull request closed without merging**
