### PR TITLE
Issues/29 port gatk germline pipeline (resolves #29)

### LINKED ISSUE #29: Port Beau's best practice GATK pipeline for germline variants to Toil
Supersedes BD2kGenomics/toil#302

### PR DESCRIPTION
**Pull request by jpfeil**
Resolves #29

### CODE REVIEW

**Comment by jvivian** [comment]
@jpfeil -- If you're satisfied, I will go ahead and merge this.  No rush if you plan on adding docstrings or whatnot.

**Comment by jpfeil** [comment]
@jvivian I am ready to merge the germline pipeline.

**Comment by jvivian** [comment]
@jpfeil  As discussed yesterday, ping me once you've committed a "readme" in this same directory.

**Comment by jvivian** [comment]
@jpfeil , some small suggestions (I'd just commit them, but I don't have write privileges to your repo)

1. Can you mention somewhere that samples must comply with b37 (i.e. no **chr** prefix). 
2. Mention that your pipeline (as is) cannot accept encrypted data (I only suggest mentioning this since our other pipelines generally download encrypted data).
3. I'd remove "exhaustive" from the description at the beginning. 

Otherwise looks great! Nice job

**Comment by jpfeil** [comment]
@jvivian Thanks John! I made the changes you suggested.

**Pull request merged**
