### PR TITLE
Add support for downloading s3:// URLs using Boto across all pipelines

### PR DESCRIPTION
**Pull request by hannes-ucsc**
plus cosmetics

### CODE REVIEW

**Comment by fnothaft** [comment]
Testing this now... Tagged with `needs work` until I've run through the testing.

**Comment by hannes-ucsc** [comment]
Removed the workdir check and force-pushed.

**Comment by fnothaft** [comment]
Thanks @hannes-ucsc . There are merge conflicts between this and #118 but they are fairly small. I have locally resolved them and am running the tests now.

**Comment by hannes-ucsc** [comment]
This was merged as part of #123.

**Pull request closed without merging**
