### PR TITLE
Cleanup HDFS on Spark failure (resolves #105, fixes #194)

### LINKED ISSUE #105: Spark jobs should clean up HDFS on failure
We should wrap all Spark jobs that write to HDFS so that if they fail (catch exception from `call_docker`), we clean up the output they wrote and rethrow the exception. If not, we can get job failure loops that we can never exit.

### LINKED ISSUE #194: File names for intermediate files on standalone Spark cluster conflict between samples
All output should go into an HDFS subdirectory. This will help with #105 because it would let us do a recursive rm on the directory for emergency clean-up. Unused intermediate files should still be removed eagerly on a file-by-file basis.

### PR DESCRIPTION
**Pull request by almussel**
Resolves #105. Also includes string processing cleanup in adam pipeline

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Doesn't this also address #194?

**Comment by fnothaft** [comment]
LGTM. I think this does resolve #194 as well. Thanks @almussel!

**Comment by hannes-ucsc** [comment]
Ignore the Jenkins failures for now. Until #190 is merged builds will always fail.

**Comment by hannes-ucsc** [comment]
+1 from me

**Pull request merged**
