### PR TITLE
Issues/29 port gatk germline pipeline

### PR DESCRIPTION
**Pull request by jpfeil**
Added preprocessing script for the GATK germline pipeline.

### CODE REVIEW

**Comment by jvivian** [comment]
@fnothaft -- Do you want to work on this PR or should I merge it now?

**Comment by fnothaft** [comment]
Thanks @jpfeil! Have you tested this on your side? If you've tested, then I am good for merge @jvivian.

**Comment by jpfeil** [comment]
No problem! I tested it on single machine and it works. @jvivian @fnothaft

**Comment by fnothaft** [comment]
Thanks @jpfeil! @jvivian this is good to go from my side.

**Pull request merged**
