### PR TITLE
Improve speed of RNA-seq CI (resolves #254)

### LINKED ISSUE #254: Improve speed of RNA-seq CI
Use new inputs generated for BWA CI

### PR DESCRIPTION
**Pull request by jvivian**
Improve speed of RNA-seq CI (resolves #254)

### CODE REVIEW

**Comment by jvivian** [comment]
@hannes-ucsc — Rebased onto master

**Comment by hannes-ucsc** [comment]
Commit title lacks issue reference.

I also think that the PR title is better. You could just use that for the commit title.

**Comment by jvivian** [comment]
@hannes-ucsc Fixed commit message.

**Comment by hannes-ucsc** [comment]
Conflicts.

**Comment by jvivian** [comment]
@hannes-ucsc it has the *needs work* label ;)

**Comment by jvivian** [comment]
@hannes-ucsc — Ready

**Comment by hannes-ucsc** [comment]
AFAICT, commits cb4d3b1 and d2fced4 are redundant and should be removed.

**Comment by jvivian** [comment]
jenkins, test this please

**Comment by jvivian** [comment]
> AFAICT, commits cb4d3b1 and d2fced4 are redundant and should be removed.

Ya, there was an issue with rebase and it refused to squash those 2 commits. I reset to master and reapplied the commit.

**Pull request merged**
