### PR TITLE
Picking commits from #328

### PR DESCRIPTION
**Pull request by fnothaft**
@hannes-ucsc let me know if you want me to open an issue for this. I spoke with @jvivian and he is blocked on some of the fixes in #328, while we debug the spark service update. I figured it'd be wise to open a PR with those commits picked over, so we can merge the Toil 3.2.1 fixes and get @jvivian on his merry way.

### CODE REVIEW

**Comment by jvivian** [comment]
Thanks @fnothaft !

**Comment by jvivian** [comment]
LG2M (assuming tests pass)

**Comment by hannes-ucsc** [comment]
No issue needed. But the commit messages are mostly crap. Not your problem, though, @fnothaft.

**Comment by fnothaft** [comment]
Thank you; you are a good person. May your day be joyous.

**Comment by jvivian** [comment]
@hannes-ucsc — Ready for review

**Pull request merged**
