### PR TITLE
Setup CI for alignment pipeline (resolves #239)

### LINKED ISSUE #239: Setup CI for alignment pipeline

### PR DESCRIPTION
**Pull request by jvivian**

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
The title `Sneak in` commit should describe what it fixes. In the grand scheme of things (when we look at the history one year from now) it's irrelevant that the change was snuck in as part of an unrelated PR.

**Comment by jvivian** [comment]
@hannes-ucsc Jenkins build fails due to timeout of bwa test.   On Openstack (15 cores), it runs in 7 minutes but on a 2 core m3.large the BWA algorithm is too cpu intensive to finish within 30m even for a very small input (~160M).   I looked on the Jenkins slave and can see by the tmp directory that BWA was almost finished running.  We could make the toil-scripts slave a little beefier and it should go through — I'd recommend a c3.large as the best price point at 4-cores.

**Comment by hannes-ucsc** [comment]
Made instance type c3.large and bumped timeout to 45min.

Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
In the long run, we should separate out a special slave roles in cgcloud for the toil-scripts and cgl-docker-lib: https://github.com/BD2KGenomics/cgcloud/issues/154

**Comment by hannes-ucsc** [comment]
Bumped timeout to 1h.

Jenkins, test this please.

**Comment by jvivian** [comment]
BWA CI is failing for some reason, unfortunately I don't get a stacktrace or anything from jenkins console output — looking into it now.

**Comment by jvivian** [comment]
Just tested this on an m3.large toil-jenkins-slave and it ran in 31 minutes and _passed_.   I made some even smaller inputs (1MB down from 150MB), to see if i can get it to run in a couple minutes, but I'm a bit confused why the last jenkins build marked bwa_alignment as failed...
screen shot 2016-04-28 at 2 26 55 pm

**Comment by jvivian** [comment]
@hannes-ucsc — Tests pass now.  Using the sample improvements I made here to speed up the RNA-seq CGL pipeline CI tests #254

**Pull request merged**
