### PR TITLE
Refactor packaging

### PR DESCRIPTION
**Pull request by fnothaft**
This is just the two commits that refactor the package structure of toil-scripts from #73. @hannes-ucsc suggested that we split these out into a separate PR that can merge quickly, as to not block development, which I agree with. I am still working to address the following two comments that @hannes-ucsc made on #73:

> 3. User scripts (or rather user modules) must be invoked with python -m followed by a fully-qualified module path, e.g. ...

> 5. Some of the module and package names are a bit long, maybe we can remove the _pipeline from the end of module or package names. We could also adopt the convention of always naming user modules toil.py or main.py. The above example would then become ...

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
@jvivian, are you ok with this? It will break your wrapper scripts!

**Comment by jvivian** [comment]
@hannes-ucsc The fix will be changing `python <script>.py` to `python -m <script>.py` in the wrappers, correct?  This will cause a bunch of merge conflicts for me, but I don't mind dealing it.  Better to just treat it like a band-aid and merge now.

**Comment by hannes-ucsc** [comment]
@jvivian Not quite, the current directory needs to be src, the -m arg needs to be a fully qualified module path, not a relative script file path. See https://github.com/BD2KGenomics/toil-scripts/pull/73#issuecomment-169592209 for details.

**Comment by hannes-ucsc** [comment]
@jvivian Instead of changing cwd to src, you can also make sure that the absolute path to src is in PYTHONPATH. I think I'll just go ahead and fix the wrapper scripts. In a continuation PR.

**Comment by fnothaft** [comment]
@hannes-ucsc if you want to open a PR against my fork/branch with the module path changes, then we can get this all in a single PR.

**Comment by hannes-ucsc** [comment]
Continued in #77.

**Pull request closed without merging**
