### PR TITLE
Überscript cleanup

### PR DESCRIPTION
**Pull request by hannes-ucsc**
Mainly deduplications, consistency, and some simplifications.

I'm hoping to get this reviewed and merged quickly because I touched a lot of lines making this prone to becoming stale quickly.

### CODE REVIEW

**Comment by fnothaft** [comment]
Thanks @hannes-ucsc; will look in a bit.

**Comment by fnothaft** [comment]
LGTM! Just passed through all of the commits and just had the one comment on https://github.com/BD2KGenomics/toil-scripts/commit/3cfdc2d42c36030dc59662dc1bdf281496901fd8. Once that is resolved, this is good to merge from my side.

**Comment by hannes-ucsc** [comment]
Modified 3cfdc2d42c36030dc59662dc1bdf281496901fd8 to reflect your suggestion: 46ce65ed3b5d407b6897e2bd58aabc7a1841060b. Also added removal of some trailing whitespace to the last commit in this PR.

**Comment by hannes-ucsc** [comment]
@fnothaft thank you for the quick review.

**Pull request merged**
