### PR TITLE
Backport mate-pair heuristic and add disk req (resolves #454, resolves #455)

### LINKED ISSUE #454: Disk requirement missing in rnaseq pipeline
… in the job for conditional bam upload.

### LINKED ISSUE #455: Backport fastq mate pair naming fix to 2.0.x

### PR DESCRIPTION
**Pull request by jvivian**
resolves #454, resolves #455

### CODE REVIEW

**Comment by jvivian** [comment]
@hannes-ucsc — Ready for review.  "Mate pair heuristic" is a direct cherrypick from the branch that was merged into master.

**Comment by hannes-ucsc** [comment]
I think you're missing 76d1db418116c5e203f23612baecc52a09bffa48 and maybe 8762fcd4654eb660a50374d47f27895e20fc2eff. You may want to make it a habit to squash the review edits into the original commits so this doesn't happen. 

Also, 1fb6f4f0e39ce502360847e44da5670184a3c1f6 does not look like a cherry-picked commit. I think we should distinguish between actual CPs (the ones that get merged automatically) and manual back-ports.

**Comment by hannes-ucsc** [comment]
I think with the new GH review feature, we can do away with the `needs work` tag.

**Comment by jvivian** [comment]
Thanks @hannes-ucsc — sloppy work, can't believe i missed that.

**Comment by jvivian** [comment]
@hannes-ucsc — Ready for review

**Pull request merged**
