### PR TITLE
Refactor rnaseq cgl pipeline (resolves #221)

### LINKED ISSUE #221: Refactor rnaseq_cgl pipeline
In preparation for releases/2.0, Dockerizing the pipelines, and code shame:

- Get rid of dictionaries wherever possible
- Fix convoluted static declaration to allow use of `consolidate_tarballs_job` library function
- Clean-up processing steps 
- Any other crufty bits I find

### PR DESCRIPTION
**Pull request by jvivian**
Based off of #190

### CODE REVIEW

**Comment by jvivian** [comment]
Jenkins, test this please.

**Comment by jvivian** [comment]
@hannes-ucsc

**Comment by hannes-ucsc** [comment]
Looks good. TY. I will merge once rebased and conflicts resolve.

**Comment by jvivian** [comment]
@hannes-ucsc

**Pull request merged**
